### PR TITLE
AIX: make libfastjson compatible with AIX

### PR DESCRIPTION
**Pull request by rgerhards**
Note: I am doing this PR on behalf of the original commitor (with his permission), as he did not want to file a PR on github but rather sent me a patch file.

### CODE REVIEW

**Comment by rgerhards** [comment]
@purnimam1 please have a look at the Travis tests. It fails due to code style issue. My apologies that this is not yet fully documented. We require tabs for indention.

**Comment by purnimam1** [comment]
Hi Rainer
 
 
This is my first time on github so would appreciate if you can help me a bit.
 
So when I see in vi I see that lines above and below the concerned patch is also using Tab spaces.
 
static int vasprintf(char **buf, const char *fmt, va_list ap)${$^Iint chars;$^Ichar *b;$#ifdef _AIX $^Istatic char _T_emptybuffer = '\0';$#endif $
 
So pleas let me know what needs to be fixed here .
 
I also saw failures for rsyslog PR that I created . WIll try to address them as well.
 
So since the code has not yet been pulled in I need to do  change the files , commit,push the file again ? Correct ?
 
ThanksPurnima.MIndia Software & Technology LabsIBM India Pvt Ltd.Ph: 080-41777468Mail to : purnima.m@in.ibm.com
 
 
----- Original message -----From: Rainer Gerhards <notifications@github.com>To: rsyslog/libfastjson <libfastjson@noreply.github.com>Cc: Purnima Madanamanoharan/India/IBM@IBMIN, Mention <mention@noreply.github.com>Subject: Re: [rsyslog/libfastjson] AIX: make libfastjson compatible with AIX (#121)Date: Fri, Nov 4, 2016 6:38 PM 
@purnimam1 please have a look at the Travis tests. It fails due to code style issue. My apologies that this is not yet fully documented. We require tabs for indention.

**Comment by davidelang** [comment]
I think what he is saying is that the rsyslog standard is to use tabs for indentation, but somewhere in your PR you use spaces instead. Please check and replace them with tabs.

**Comment by rgerhards** [comment]
2016-11-05 11:28 GMT+01:00 purnimam1 <notifications@github.com>:

> This is my first time on github so would appreciate if you can help me a
> bit.
>

We are very happy to have us help with the AIX port, and we will of course
help you get forword.


>
> So when I see in vi I see that lines above and below the concerned patch
> is also using Tab spaces.
>
> static int vasprintf(char **buf, const char *fmt, va_list ap)${$^Iint
> chars;$^Ichar *b;$#ifdef _AIX $^Istatic char _T_emptybuffer = '\0';$#endif $
>

As a suggestion, messages like this are best posted via the github
interface, because this permits you to use ``` to quote code ``` (maybe
this works via mail as well, let's see). This will permit code to display
nicely.

I'll create a CONTRIBUTING file with the details that have been fixed so
far (code style is currently under discussion).


> So pleas let me know what needs to be fixed here .
>
> I also saw failures for rsyslog PR that I created . WIll try to address
> them as well.


> So since the code has not yet been pulled in I need to do  change the
> files , commit,push the file again ? Correct ?
>

Yes, that's the basic workflow. Here in this PR we have the problem that I
have created it, so you cannot push to it. And for me it requires quite
some work to follow. So I think the best thing is that I close this PR here
as unmerged and you create your own, which you then can modify as needed in
the future.

Thanks again for your work!
Rainer

>

**Comment by rgerhards** [comment]
As a side-note, the failing travis test shows where the SP/TAB problem is.

**Comment by rgerhards** [comment]
@purnimam1 I have added some basic doc on codestyle and contribution policies. To be extended...

see https://github.com/rsyslog/libfastjson/blob/master/CONTRIBUTING.md

**Comment by rgerhards** [comment]
Closing this now so that @purnimam1 can do his own PR.

**Pull request closed without merging**
